import type { Request } from 'express';
import type { Types } from 'mongoose';

/** Allowed values for task workflow status. */
export const TASK_STATUSES = ['cancelled', 'todo', 'in_progress', 'test', 'done'] as const;

/** Allowed values for task priority. */
export const TASK_PRIORITIES = ['low', 'medium', 'high'] as const;

/** Allowed values for embedded project status on a client. */
export const PROJECT_STATUSES = ['cancelled', 'pending', 'active', 'completed', 'paused'] as const;

export type TaskStatus = (typeof TASK_STATUSES)[number];
export type TaskPriority = (typeof TASK_PRIORITIES)[number];
export type ProjectStatus = (typeof PROJECT_STATUSES)[number];

/**
 * Team member embedded in a client document.
 */
export interface TeamMember {
  name: string;
  role?: string;
  email?: string;
  notes?: string;
}

/**
 * Project embedded in a client document.
 * `_id` is generated by Mongoose for subdocuments.
 */
export interface Project {
  _id?: Types.ObjectId;
  name: string;
  description?: string;
  status: ProjectStatus;
  createdAt?: Date;
}

/**
 * Authenticated request with the resolved user id from JWT middleware.
 */
export interface AuthRequest extends Request {
  userId: string;
}

/**
 * Payload encoded in JWT access tokens.
 */
export interface JwtPayload {
  userId: string;
}

/**
 * Public user fields returned by auth endpoints.
 */
export interface UserPublic {
  id: string;
  email: string;
  name: string;
  createdAt: Date;
}

/**
 * Response shape for register and login endpoints.
 */
export interface AuthResponse {
  token: string;
  user: UserPublic;
}
